language: node_js
node_js:
    - "lts/*"

before_install:
    - npm install -g npm@latest

install:
    - npm i

script:
    - npm run build

before_deploy:
    - ./bin/fiddleWithGitIgnore.sh
    - npm prune --production

deploy:
    provider: azure_web_apps
