#!/bin/bash
SCRIPT_DIR="${BASH_SOURCE[0]%\\*}"
SCRIPT_DIR="${SCRIPT_DIR%/*}"

DEPLOYMENT_SOURCE=$SCRIPT_DIR/public
DEPLOYMENT_TARGET=$SCRIPT_DIR/../wwwroot

rm -rf $DEPLOYMENT_TARGET/public
cp -rf $DEPLOYMENT_SOURCE $DEPLOYMENT_TARGET

echo "Finished successfully."
